[project]
name = "gold-ledger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.0",
    "bcrypt>=4.2.1",
    "dependency-injector>=4.45.0",
    "fastapi>=0.115.6",
    "httpx>=0.28.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.10",
    "pydantic[email]>=2.10.5",
    "pydantic-settings>=2.7.1",
    "python-jose[cryptography]>=3.3.0",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.37",
    "typer>=0.15.1",
    "uvicorn[standard]>=0.34.0",
    "rich>=13.9.4",
    "pillow>=11.1.0",
    "boto3>=1.36.2",
    "shortuuid>=1.0.13",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "pytest>=8.3.4",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
gold_ledger = "app.cli:app"
