"""cache

Revision ID: 12dd310cd2e1
Revises: 3505169e0808
Create Date: 2025-02-05 18:42:51.413794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12dd310cd2e1"
down_revision: Union[str, None] = "3505169e0808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column("cash_products", sa.DECIMAL(), nullable=False),
        sa.Column("cash_payments", sa.DECIMAL(), nullable=False),
        sa.Column("cash_due_date", sa.Date(), nullable=True),
        sa.Column("cash_to_pay", sa.DECIMAL(), nullable=False),
        sa.Column("rtgs_products", sa.DECIMAL(), nullable=False),
        sa.Column("rtgs_payments", sa.DECIMAL(), nullable=False),
        sa.Column("rtgs_due_date", sa.Date(), nullable=True),
        sa.Column("rtgs_to_pay", sa.DECIMAL(), nullable=False),
        sa.Column("fine_products", sa.DECIMAL(), nullable=False),
        sa.Column("fine_payments", sa.DECIMAL(), nullable=False),
        sa.Column("fine_due_date", sa.Date(), nullable=True),
        sa.Column("fine_to_pay", sa.DECIMAL(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cache_supplier_retailer",
        "cache",
        ["supplier_id", "retailer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cache_retailer_id"), "cache", ["retailer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cache_retailer_id"), table_name="cache")
    op.drop_index("idx_cache_supplier_retailer", table_name="cache")
    op.drop_table("cache")
    # ### end Alembic commands ###
