"""rate

Revision ID: 21ea4c976a7c
Revises: 6d28110c38b2
Create Date: 2025-02-01 16:56:48.332119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21ea4c976a7c"
down_revision: Union[str, None] = "6d28110c38b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "rate_per_gram",
        new_column_name="rate",
        existing_type=sa.DECIMAL(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "rate",
        new_column_name="rate_per_gram",
        existing_type=sa.DECIMAL(),
        nullable=False,
    )
    # ### end Alembic commands ###
