"""payment_note

Revision ID: 360958fe1042
Revises: 12dd310cd2e1
Create Date: 2025-02-08 14:22:53.533821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "360958fe1042"
down_revision: Union[str, None] = "12dd310cd2e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "note")
    # ### end Alembic commands ###
