"""nullable_payment

Revision ID: 56859132552c
Revises: d736902f9387
Create Date: 2025-01-26 16:21:26.215033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56859132552c"
down_revision: Union[str, None] = "d736902f9387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payments", "weight", existing_type=sa.NUMERIC(), nullable=True)
    op.alter_column("payments", "quality", existing_type=sa.NUMERIC(), nullable=True)
    op.alter_column(
        "payments", "rate_per_gram", existing_type=sa.NUMERIC(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments", "rate_per_gram", existing_type=sa.NUMERIC(), nullable=False
    )
    op.alter_column("payments", "quality", existing_type=sa.NUMERIC(), nullable=False)
    op.alter_column("payments", "weight", existing_type=sa.NUMERIC(), nullable=False)
    # ### end Alembic commands ###
