"""remove_activities

Revision ID: 57ef686b71b1
Revises: cab85e73eae3
Create Date: 2025-02-03 21:10:34.471727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "57ef686b71b1"
down_revision: Union[str, None] = "cab85e73eae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_activity_supplier_retailer_created", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("type", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("retailer_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("payment_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name="activities_payment_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name="activities_product_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"], ["retailers.id"], name="activities_retailer_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name="activities_supplier_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="activities_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="activities_pkey"),
    )
    op.create_index(
        "idx_activity_supplier_retailer_created",
        "activities",
        ["supplier_id", "retailer_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
