"""candelled_by

Revision ID: 6d28110c38b2
Revises: cb558d3b31cc
Create Date: 2025-02-01 16:04:41.337063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d28110c38b2"
down_revision: Union[str, None] = "cb558d3b31cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("cancelled_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "payments", "users", ["cancelled_by"], ["id"])
    op.add_column("products", sa.Column("cancelled_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "products", "users", ["cancelled_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "cancelled_by")
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_column("payments", "cancelled_by")
    # ### end Alembic commands ###
