"""payments

Revision ID: 735154c3c739
Revises: 8f0cd48aa2ba
Create Date: 2025-01-25 18:42:40.949616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735154c3c739'
down_revision: Union[str, None] = '8f0cd48aa2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('weight', sa.DECIMAL(), nullable=False),
    sa.Column('quality', sa.DECIMAL(), nullable=False),
    sa.Column('rate_per_gram', sa.DECIMAL(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_supplier_retailer_created', 'payments', ['supplier_id', 'retailer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_retailer_id'), 'payments', ['retailer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_retailer_id'), table_name='payments')
    op.drop_index('idx_payments_supplier_retailer_created', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
