"""products_index

Revision ID: 738de1a71378
Revises: de1340f9e931
Create Date: 2025-01-19 15:38:26.036009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "738de1a71378"
down_revision: Union[str, None] = "de1340f9e931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_products_supplier_retailer_created",
        "products",
        ["supplier_id", "retailer_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_retailer_id"), "products", ["retailer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_retailer_id"), table_name="products")
    op.drop_index("idx_products_supplier_retailer_created", table_name="products")
    # ### end Alembic commands ###
