"""product_date

Revision ID: 7437a2231cad
Revises: 735154c3c739
Create Date: 2025-01-25 23:37:24.512042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7437a2231cad"
down_revision: Union[str, None] = "735154c3c739"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "payment_due_date", sa.Date(), server_default="2025-12-31", nullable=False
        ),
    )
    op.alter_column(
        "products",
        "date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("products", "payment_due_date")
    # ### end Alembic commands ###
