"""due_payments

Revision ID: 826c94376bfc
Revises: 360958fe1042
Create Date: 2025-02-08 15:13:35.640347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "826c94376bfc"
down_revision: Union[str, None] = "360958fe1042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cache",
        sa.Column("due_payments", sa.JSON(), server_default="[]", nullable=False),
    )
    op.drop_column("cache", "cash_to_pay")
    op.drop_column("cache", "cash_due_date")
    op.drop_column("cache", "rtgs_to_pay")
    op.drop_column("cache", "fine_to_pay")
    op.drop_column("cache", "rtgs_due_date")
    op.drop_column("cache", "fine_due_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cache",
        sa.Column("fine_due_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "cache",
        sa.Column("rtgs_due_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "cache",
        sa.Column("fine_to_pay", sa.NUMERIC(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "cache",
        sa.Column("rtgs_to_pay", sa.NUMERIC(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "cache",
        sa.Column("cash_due_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "cache",
        sa.Column("cash_to_pay", sa.NUMERIC(), autoincrement=False, nullable=False),
    )
    op.drop_column("cache", "due_payments")
    # ### end Alembic commands ###
