"""admin_to_owner

Revision ID: 8e82743c60fd
Revises: d4fa941a06fa
Create Date: 2025-01-25 12:18:04.827377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e82743c60fd"
down_revision: Union[str, None] = "d4fa941a06fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("retailer_stores_admin_id_fkey", "retailers", type_="foreignkey")
    op.drop_constraint("supplier_stores_admin_id_fkey", "suppliers", type_="foreignkey")

    op.alter_column("suppliers", "admin_id", new_column_name="owner_id")
    op.alter_column("retailers", "admin_id", new_column_name="owner_id")

    op.create_foreign_key(
        "retailer_stores_owner_id_fkey", "retailers", "users", ["owner_id"], ["id"]
    )
    op.create_foreign_key(
        "supplier_stores_owner_id_fkey", "suppliers", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("retailer_stores_owner_id_fkey", "retailers", type_="foreignkey")
    op.drop_constraint("supplier_stores_owner_id_fkey", "suppliers", type_="foreignkey")

    op.alter_column("retailers", "owner_id", new_column_name="admin_id")
    op.alter_column("suppliers", "owner_id", new_column_name="admin_id")

    op.create_foreign_key(
        "retailer_stores_admin_id_fkey", "retailers", "users", ["admin_id"], ["id"]
    )
    op.create_foreign_key(
        "supplier_stores_admin_id_fkey", "suppliers", "users", ["admin_id"], ["id"]
    )
    # ### end Alembic commands ###
