"""connenctions

Revision ID: a7207878c5d1
Revises: 826c94376bfc
Create Date: 2025-02-15 17:32:42.702492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7207878c5d1"
down_revision: Union[str, None] = "826c94376bfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connections_retailer_id"), "connections", ["retailer_id"], unique=False
    )
    op.create_index(
        op.f("ix_connections_supplier_id"), "connections", ["supplier_id"], unique=False
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("retailer_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invites_code"), "invites", ["code"], unique=True)
    op.execute(
        "INSERT INTO connections (supplier_id, retailer_id) SELECT supplier_id, retailer_id FROM cache;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invites_code"), table_name="invites")
    op.drop_table("invites")
    op.drop_index(op.f("ix_connections_supplier_id"), table_name="connections")
    op.drop_index(op.f("ix_connections_retailer_id"), table_name="connections")
    op.drop_table("connections")
    # ### end Alembic commands ###
