"""confirmed_rejected

Revision ID: bcece8dc448a
Revises: 56859132552c
Create Date: 2025-01-26 17:36:51.069662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcece8dc448a"
down_revision: Union[str, None] = "56859132552c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("confirmed_by", sa.Integer(), nullable=True))
    op.add_column("payments", sa.Column("rejected_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "payments", "users", ["confirmed_by"], ["id"])
    op.create_foreign_key(None, "payments", "users", ["rejected_by"], ["id"])
    op.add_column("products", sa.Column("confirmed_by", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("rejected_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "products", "users", ["confirmed_by"], ["id"])
    op.create_foreign_key(None, "products", "users", ["rejected_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "rejected_by")
    op.drop_column("products", "confirmed_by")
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_column("payments", "rejected_by")
    op.drop_column("payments", "confirmed_by")
    # ### end Alembic commands ###
