"""remove_rate_per_gram

Revision ID: c98b61869b2b
Revises: 72f585dc2bf1
Create Date: 2025-01-31 17:10:21.245661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c98b61869b2b"
down_revision: Union[str, None] = "72f585dc2bf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "rate_per_gram")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("rate_per_gram", sa.NUMERIC(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
