"""status

Revision ID: cab85e73eae3
Revises: 21ea4c976a7c
Create Date: 2025-02-01 21:26:44.779332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cab85e73eae3"
down_revision: Union[str, None] = "21ea4c976a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("status", sa.Integer(), server_default="1", nullable=False),
    )

    op.execute("UPDATE payments SET status = 2 WHERE confirmed_by IS NOT NULL;")
    op.execute("UPDATE payments SET status = 3 WHERE rejected_by IS NOT NULL;")
    op.execute("UPDATE payments SET status = 4 WHERE cancelled_by IS NOT NULL;")

    op.add_column(
        "products",
        sa.Column("status", sa.Integer(), server_default="1", nullable=False),
    )

    op.execute("UPDATE products SET status = 2 WHERE confirmed_by IS NOT NULL;")
    op.execute("UPDATE products SET status = 3 WHERE rejected_by IS NOT NULL;")
    op.execute("UPDATE products SET status = 4 WHERE cancelled_by IS NOT NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "status")
    op.drop_column("payments", "status")
    # ### end Alembic commands ###
