"""amount_nullable

Revision ID: cb558d3b31cc
Revises: d0ac377fcfeb
Create Date: 2025-02-01 14:25:12.784243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb558d3b31cc"
down_revision: Union[str, None] = "d0ac377fcfeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "total_amount",
        new_column_name="amount",
        existing_type=sa.DECIMAL(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "amount",
        new_column_name="total_amount",
        existing_type=sa.DECIMAL(),
        nullable=False,
    )
    # ### end Alembic commands ###
