"""product_payment

Revision ID: d0ac377fcfeb
Revises: c98b61869b2b
Create Date: 2025-02-01 13:33:45.586951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "d0ac377fcfeb"
down_revision: Union[str, None] = "c98b61869b2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "total_amount",
        new_column_name="payment_amount",
        nullable=True,
    )
    op.add_column("products", sa.Column("payment_quality", sa.DECIMAL(), nullable=True))
    op.add_column("products", sa.Column("payment_weight", sa.DECIMAL(), nullable=True))
    op.drop_column("products", "custom_fields")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "payment_amount",
        new_column_name="total_amount",
        nullable=False,
    )

    op.add_column(
        "products",
        sa.Column(
            "custom_fields",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("products", "payment_weight")
    op.drop_column("products", "payment_quality")
    # ### end Alembic commands ###
