"""product_images

Revision ID: d4fa941a06fa
Revises: 98a28a40c305
Create Date: 2025-01-23 18:36:17.110439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4fa941a06fa"
down_revision: Union[str, None] = "98a28a40c305"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
    )
    op.create_index(
        "idx_product_images_product_image",
        "product_images",
        ["product_id", "image_id"],
        unique=True,
    )
    op.drop_column("products", "picture")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "picture",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("idx_product_images_product_image", table_name="product_images")
    op.drop_table("product_images")
    # ### end Alembic commands ###
