"""product

Revision ID: de1340f9e931
Revises: 8d0d967b1736
Create Date: 2025-01-19 15:34:17.306476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de1340f9e931"
down_revision: Union[str, None] = "8d0d967b1736"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("weight", sa.DECIMAL(), nullable=False),
        sa.Column("quality", sa.DECIMAL(), nullable=False),
        sa.Column("rate_per_gram", sa.DECIMAL(), nullable=False),
        sa.Column("total_amount", sa.DECIMAL(), nullable=False),
        sa.Column("custom_fields", sa.JSON(), nullable=False),
        sa.Column("picture", sa.JSON(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailer_stores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier_stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
