"""rid_of_store

Revision ID: df09aada697d
Revises: 738de1a71378
Create Date: 2025-01-21 20:23:36.867524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df09aada697d"
down_revision: Union[str, None] = "738de1a71378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("products_retailer_id_fkey", "products", type_="foreignkey")
    op.drop_constraint("products_supplier_id_fkey", "products", type_="foreignkey")
    op.drop_constraint("users_supplier_store_id_fkey", "users", type_="foreignkey")
    op.drop_constraint("users_retailer_store_id_fkey", "users", type_="foreignkey")

    op.alter_column("users", "retailer_store_id", new_column_name="retailer_id")
    op.alter_column("users", "supplier_store_id", new_column_name="supplier_id")

    op.rename_table("retailer_stores", "retailers")
    op.rename_table("supplier_stores", "suppliers")

    op.create_foreign_key(
        "products_retailer_id_fkey", "products", "retailers", ["retailer_id"], ["id"]
    )
    op.create_foreign_key(
        "products_supplier_id_fkey", "products", "suppliers", ["supplier_id"], ["id"]
    )

    op.create_foreign_key(
        "users_retailer_store_id_fkey", "users", "retailers", ["retailer_id"], ["id"]
    )
    op.create_foreign_key(
        "users_supplier_store_id_fkey", "users", "suppliers", ["supplier_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("products_retailer_id_fkey", "products", type_="foreignkey")
    op.drop_constraint("products_supplier_id_fkey", "products", type_="foreignkey")
    op.drop_constraint("users_supplier_store_id_fkey", "users", type_="foreignkey")
    op.drop_constraint("users_retailer_store_id_fkey", "users", type_="foreignkey")

    op.alter_column("users", "supplier_id", new_column_name="supplier_store_id")
    op.alter_column("users", "retailer_id", new_column_name="retailer_store_id")

    op.rename_table("retailers", "retailer_stores")
    op.rename_table("suppliers", "supplier_stores")

    op.create_foreign_key(
        "products_retailer_id_fkey",
        "products",
        "supplier_stores",
        ["supplier_id"],
        ["id"],
    )
    op.create_foreign_key(
        "products_supplier_id_fkey",
        "products",
        "retailer_stores",
        ["retailer_id"],
        ["id"],
    )

    op.create_foreign_key(
        "users_supplier_store_id_fkey",
        "users",
        "supplier_stores",
        ["supplier_store_id"],
        ["id"],
    )
    op.create_foreign_key(
        "users_retailer_store_id_fkey",
        "users",
        "retailer_stores",
        ["retailer_store_id"],
        ["id"],
    )
    # ### end Alembic commands ###
