"""remove_role

Revision ID: e7d052da9938
Revises: 8e82743c60fd
Create Date: 2025-01-25 12:43:11.671538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7d052da9938"
down_revision: Union[str, None] = "8e82743c60fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
